version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Oslo"
    target-branch: "dev"
    reviewers:
      - "reliaboe"

  - package-ecosystem: "nuget"
    directory: "/src/server"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Oslo"
    target-branch: "dev"
    reviewers:
      - "reliaboe"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Oslo"
    target-branch: "dev"
    reviewers:
      - "reliaboe"
