name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please search to see if an issue already exists for the bug you encountered before creating a new report.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Describe how to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        e.g.
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen if the application was working correctly.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: A description of which platform and software the bug occured on.
      value: |
        Device: [e.g. desktop computer, mobile (please include model)]
        OS:
        Browser:
        Version:
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If you have relevant screenshots, error messages or anything else you can provide it here.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
