name: Feature Request
description: Suggest an idea for a new feature for this project
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what your idea is.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: |
        If you have relevant images/screenshots or anything else you can provide it here.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
