name: Deploy client and server to Dockerhub

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:

  # Deploy server to Dockerhub
  deploy-server-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mimirorg/typelibrary-server
          tags: |
            ${{ inputs.tags }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./src/server
          file: ./src/server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: final

  # Deploy client to Dockerhub
  deploy-client-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mimirorg/typelibrary-client
          tags: |
            ${{ inputs.tags }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./src/client
          file: ./src/client/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: final