name: Build and push to Dockerhub

on:
  workflow_call:
    inputs:
      build-target:
        description: Must be either client or server
        required: true
        type: string
      tags:
        description: A list of tags to use for the docker image, delimited by line breaks
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  validate-build-target:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if build target is not valid
        if: inputs.build-target != 'client' && inputs.build-target != 'server'
        run: exit 1
      - name: Succeed otherwise
        run: |
          echo 'Build target ${{ inputs.build-target }} is valid'

  build-and-push:
    needs: validate-build-target
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ format('mimirorg/tyle-{0}', inputs.build-target) }}
          tags: |
            ${{ inputs.tags }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: ${{ format('Build and push {0}', inputs.build-target) }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ format('./src/{0}', inputs.build-target) }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: final