name: Deploy client and server to Dockerhub

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      DOCKER_SECRETS:
        required: true

jobs:

  # Deploy client and server to Dockerhub
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./src/server
          file: ./src/server/Dockerfile
          push: true
          secrets: ${{ secrets.DOCKER_SECRETS }}
          tags: ${{ inputs.tags }}
          target: final

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./src/client
          file: ./src/client/Dockerfile
          push: true
          secrets: ${{ secrets.DOCKER_SECRETS }}
          tags: ${{ inputs.tags }}
          target: final
