name: CI - Code Quality

on:
  pull_request:

  push:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      client-changed: ${{ steps.changes.outputs.client }}
      server-changed: ${{ steps.changes.outputs.server }}
      docker-client-changed: ${{ steps.changes.outputs.docker-client }}
      docker-server-changed: ${{ steps.changes.outputs.docker-server }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: .github/change-filters.yaml

  ######### CLIENT ###########

  code-quality-client-build:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: tyle-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: final
      hash_files_template: "**/package-lock.json"
      upload_artefact: ${{ needs.check-for-changes.outputs.docker-client-changed == 'true' }}

  code-quality-client-test:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: tyle-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: test
      hash_files_template: "**/package-lock.json"

  code-quality-client-lint:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: tyle-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: lint
      hash_files_template: "**/package-lock.json"

  code-quality-client-format:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: tyle-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: format
      hash_files_template: "**/package-lock.json"

  ######### SERVER ###########

  code-quality-server-build:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.server-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: tyle-server
      context: ./src/server
      file: ./src/server/Dockerfile
      target: final
      hash_files_template: "**/*.csproj"
      upload_artefact: ${{ needs.check-for-changes.outputs.docker-server-changed == 'true' }}

  code-quality-server-format:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.server-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: tyle-server
      context: ./src/server
      file: ./src/server/Dockerfile
      target: format
      hash_files_template: "**/*.csproj"
      
