name: CI - MAIN

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  nuget_source: https://api.nuget.org/v3/index.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mimir-org/mimir-actions/generate-release-tag-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: ${{ steps.tag_version.outputs.new_tag != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.tag_version.outputs.new_tag }}
          name: Release  v${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true

      - name: Check Output Parameters
        if: ${{ steps.tag_version.outputs.new_tag != '' }}
        run: |
          echo "Tag: ${{ steps.release.outputs.new_tag }}"
          echo "Version: ${{ steps.release.outputs.new_version }}"

  build-client:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    needs: create-release
    if: needs.create-release.outputs.tag!=''
    with:
      repository: typelibrary-client
      tags: |
        latest
        ${{needs.create-release.outputs.tag}}
      context: ./src/client
      file: ./src/client/Dockerfile
      target: final
      hash_files_template: "**/package-lock.json"
      push: true
    secrets:
      REGISTRY_SERVER_URLS: ${{ secrets.REGISTRY_SERVER_URL }}
      REGISTRY_USERNAMES: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORDS: ${{ secrets.REGISTRY_PASSWORD }}

  build-server:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    needs: create-release
    if: needs.create-release.outputs.tag!=''
    with:
      repository: typelibrary-server
      tags: |
        latest
        ${{needs.create-release.outputs.tag}}
      context: ./src/server
      file: ./src/server/Dockerfile
      target: final
      hash_files_template: "**/*.csproj"
      push: true
    secrets:
      REGISTRY_SERVER_URLS: ${{ secrets.REGISTRY_SERVER_URL }}
      REGISTRY_USERNAMES: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORDS: ${{ secrets.REGISTRY_PASSWORD }}

  nuget-Common:
    runs-on: ubuntu-latest
    needs: create-release
    if: needs.create-release.outputs.tag!=''
    env:
      package_name: Mimirorg.Common
    defaults:
      run:
        working-directory: src/server
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build -c Release ${{env.package_name}}

      - name: Package Nuget
        run: dotnet pack -c Release --output . --include-source --include-symbols  --no-build -p:PackageVersion=${{needs.create-release.outputs.tag.substr(1)}} ${{env.package_name}}

      - name: Push
        run: dotnet nuget push ${{env.package_name}}.${{needs.create-release.outputs.tag.substr(1)}}.nupkg -k ${{secrets.NUGET_API_KEY}} --source ${{env.nuget_source}} --skip-duplicate

  nuget-TypeLibrary:
    runs-on: ubuntu-latest
    needs: create-release
    if: needs.create-release.outputs.tag!=''
    env:
      package_name: Mimirorg.TypeLibrary
    defaults:
      run:
        working-directory: src/server
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build -c Release ${{env.package_name}}

      - name: Package Nuget
        run: dotnet pack -c Release --output . --include-source --include-symbols  --no-build -p:PackageVersion=${{needs.create-release.outputs.tag.substr(1)}} ${{env.package_name}}

      - name: Push
        run: dotnet nuget push ${{env.package_name}}.${{needs.create-release.outputs.tag.substr(1)}}.nupkg -k ${{secrets.NUGET_API_KEY}} --source ${{env.nuget_source}} --skip-duplicate
