name: CI - MAIN

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  nuget_source: https://api.nuget.org/v3/index.json

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      raw_tag: ${{ steps.tag_version.outputs.raw_tag  }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mimir-org/mimir-actions/generate-release-tag-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v

      - name: Release
        if: ${{ steps.tag_version.outputs.new_tag != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.raw_tag }}
          name: Release  ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true

      - name: Check Output Parameters
        if: ${{ steps.tag_version.outputs.new_tag != '' }}
        run: |
          echo "Tag: ${{ steps.release.outputs.new_tag }}"
          echo "Version: ${{ steps.release.outputs.new_version }}"

  build-client:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    needs: create-release
    if: needs.create-release.outputs.tag!=''
    with:
      repository: typelibrary-client
      tags: |
        latest
        v${{needs.create-release.outputs.tag}}
      context: ./src/client
      file: ./src/client/Dockerfile
      target: final
      hash_files_template: "**/package-lock.json"
      push: true
      use_dockerhub: true
    secrets:
      DOCKERHUB_ORG: mimirorg
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

  build-server:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    needs: create-release
    if: needs.create-release.outputs.tag!=''
    with:
      repository: typelibrary-server
      tags: |
        latest
        v${{needs.create-release.outputs.tag}}
      context: ./src/server
      file: ./src/server/Dockerfile
      target: final
      hash_files_template: "**/*.csproj"
      push: true
      use_dockerhub: true
    secrets:
      DOCKERHUB_ORG: mimirorg
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

  npm-Typelibrary:
    runs-on: ubuntu-latest
    needs: create-release
    if: needs.create-release.outputs.raw_tag != ''
    steps:
      - uses: actions/checkout@v2

      - name: Package typescript interfaces
        run: dotnet run
        working-directory: src/server/Mimirorg.Package

      - name: Generate npm package
        run: |

          mkdir typelibrary-types

          cd typelibrary-types

          cp -a ../src/server/Mimirorg.Package/template/. ./
          
          npx tsc index.ts --declaration

          npm version ${{ needs.create-release.outputs.raw_tag }}

      - name: Publish npm package
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public --ignore-scripts
        working-directory: typelibrary-types
        env:
          NPM_TOKEN: ${{ secrets.NPM_MIMIRORG_AUTH }}

  nuget-Common:
    runs-on: ubuntu-latest
    needs: create-release
    if: needs.create-release.outputs.raw_tag != ''
    env:
      package_name: Mimirorg.Common
    defaults:
      run:
        working-directory: src/server
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build -c Release ${{env.package_name}}

      - name: Package Nuget
        run: dotnet pack -c Release --output . --include-source --include-symbols  --no-build -p:PackageVersion=${{needs.create-release.outputs.raw_tag}} ${{env.package_name}}

      - name: Push
        run: dotnet nuget push ${{env.package_name}}.${{needs.create-release.outputs.raw_tag}}.nupkg -k ${{secrets.NUGET_API_KEY}} --source ${{env.nuget_source}} --skip-duplicate

  nuget-TypeLibrary:
    runs-on: ubuntu-latest
    needs: create-release
    if: needs.create-release.outputs.raw_tag != ''
    env:
      package_name: Mimirorg.TypeLibrary
    defaults:
      run:
        working-directory: src/server
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build -c Release ${{env.package_name}}

      - name: Package Nuget
        run: dotnet pack -c Release --output . --include-source --include-symbols  --no-build -p:PackageVersion=${{needs.create-release.outputs.raw_tag}} ${{env.package_name}}

      - name: Push
        run: dotnet nuget push ${{env.package_name}}.${{needs.create-release.outputs.raw_tag}}.nupkg -k ${{secrets.NUGET_API_KEY}} --source ${{env.nuget_source}} --skip-duplicate
