name: Create Docker images on release or manual trigger

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tags:
        description: Docker image tags, separated by commas

env:
  TAGS: >
    ${{
      github.event_name == 'workflow_dispatch' && github.event.inputs.tags
      || github.event.release.tag_name
    }}

jobs:

  # Check branch and release type logic
  check-branch-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on branch and release mismatch
        if: >
          github.event_name == 'release' &&
          !((github.event.release.prerelease && github.event.release.target_commitish == 'stage')
          || (!github.event.release.prerelease && github.event.release.target_commitish == 'main'))
        run: exit 1
      - name: Succeed otherwise
        run: |
          echo 'Branch name and release type match, or action was manually triggered'

  # Output tags in the correct format, separated by newlines
  output-tags:
    runs-on: ubuntu-latest
    needs: check-branch-and-release
    outputs:
      tags: ${{ steps.output-tags.outputs.tags }}
    steps:
      - name: Output tags
        id: output-tags
        run: |
          formatted_tags=$(echo "$TAGS" | sed -e 's/ *, */%0A/g' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          echo "::set-output name=tags::$formatted_tags"

  # Build and push server and client to Dockerhub
  build-push-to-dockerhub:
    needs: output-tags
    uses: ./.github/workflows/build-client-and-server.yaml
    with:
      tags: |
        ${{ needs.output-tags.outputs.tags }}
    secrets: inherit
